### ISSUE TITLE
Apply modular scripts to currently existing scripts

### ISSUE THREAD

**Issue by andresgongora** [andresgongora/scripts#12]
- [x] Apply config to `status.sh`
- [x] Apply config to `color.sh`
- [x] Apply config to `alias.sh`
- [x] Apply `color.sh` to `status.sh`
- [x] Apply `color.sh` and `config.sh` to `fancy-bash-prompt.sh`
- [x] Update main README file with a brief description of the new modular scripts
- [x] Update README with instructions regarding how to change the configuration to the user's liking
- [x] Put all config files in a better location - dedidated folder maybe??

**Comment by andresgongora** [comment]
- [ ] Apply config to `status.sh`
- [ ] Apply config to `color.sh`
- [ ] Apply `color.sh` to `status.sh`
- [ ] Apply `color.sh` and `config.sh` to `fancy-bash-prompt.sh`

**Comment by olmari** [comment]
I was wondering similar things myself... somehow separate scripts themselves (especialy terminal related) from config but moest importantly logo... So then we'd have config(s) separately that we can provide example ofcourse, but anyones preference wouldn't be baked into script itself :)

**Comment by andresgongora** [comment]
Check the development branch out. I've already implemented some of this stuff there.
Notice that the "config" file is in the same folder as the scripts for debugging purposes, but will be such that the user may place it wherever she or he wants once it's finished :)

**Comment by andresgongora** [comment]
Just added the new version of `status.sh` using an external color configuration to branch develop

**Comment by andresgongora** [comment]
I just fixed the dependence on the current working dir in the last push to branch develop. The scripts no longer depend on where they are stored on the system. No modification to `config` needed anymore.

**Comment by andresgongora** [comment]
It's still not perfect. I'm opening up a new issue ticket with my latest concerns. But... it works!!
I'm creating a new pull request for master now.
