### ISSUE TITLE
Move all configuration files to common location

### ISSUE THREAD

**Issue by andresgongora** [andresgongora/scripts#21]
Right now it's a mess to change the configuration files. The user must really know what she is doing. I think that the configuration files should be in a more logical location.

- [x] Put configuration files in a better location
- [x] Explain how to change the configuration in the README. As of now, it does not even say that the scripts can be modified

**Comment by andresgongora** [comment]
@olmari suggests converting the current config into templates, and excluding all other config using a `.gitignore`. Then, using an install script #9, copy the template into the actual configuration file IFF it does not already exist.

But this depends on #25 for best results.

**Comment by olmari** [comment]
Install script or not, benefit of using .gitignore is that we provide default files to user (say: status.config.example), and all the files user then modifies does not conflict with examples we provide in git. Also it prevents us from pushing our own actual configuration files to git.

Only thing is that user needs to copy all the config.example files into actual config files, if there is no "installer" that deos it for user. Usually that is left to user to do with ofcourse clear mention in readme.md, but like said, some form of installer would also work.

**Comment by andresgongora** [comment]
How about:
* **/configuration_templates** contains all *.config.example files.
* **~/.config/scripts/** contain optional user config file.

I'm testing it like this now, as a lot of the configuration changes now with #25, and the behavior is exactly as desired... **but**... I don't really like the name `configuration_templates`. It's not bad, but I'd like to also consider other options before making the final call.

**Comment by andresgongora** [comment]
Addressed in #30
