### ISSUE TITLE
Unexpected comma after local IPv4 address 

### ISSUE THREAD

**Issue by andresgongora** [andresgongora/scripts#49]

**Comment by olmari** [comment]
Yeah, It comes from awk substituting linefeed to "," in order to show multiple IP-numbers. Need to figure out better listing magic to that!

**Comment by andresgongora** [comment]
The we only have to change it such that it does not get displayed if there is a single IP. But it does not happen with the external IP, right?

**Comment by olmari** [comment]
> Then we only have to change it such that it does not get displayed if there is a single IP.

Correct, also so that it will.not add the comma after last IP.

> But it does not happen with the external IP, right?

Correct, there is always only one external IP (that internet reports back).

**Comment by olmari** [comment]
I'll get on to figure some regex-magic now.

**Comment by olmari** [comment]
Fixed in https://github.com/andresgongora/scripts/commit/6f597d037a9a3f8cbb7574bae6d50f1864969ed8
