### ISSUE TITLE
Separate logo drawing and status-lines drawing

### ISSUE THREAD

**Issue by olmari** [andresgongora/scripts#52]
- [x] Separate (smart) logo and info printing
- [x] Update configuration files with new parameters
- [x] Make all status-info lines optional (allow user to hide or change their order)
- [x] Multi line info loading (required for logo)
- [x] Enable multi-colors in logo (written inside config file)
- [x] Allow to place the logo on the right instead of the left

Make logo drawing separate function and do that first, then at separate function draw statusdata lines. This way logo is easier to manage, especially if smaller than maximum lines, and then if terminal windows is too small to fit all the status data we can more easily to cut our way into the logo area.

We can use ANSI escape characters to actiave that, more info at https://unix.stackexchange.com/questions/210325/posix-command-that-moves-cursor-to-specific-position-in-terminal-window

This would also take care/include https://github.com/andresgongora/scripts/issues/42

Also here is very simple test in terminal, I made few lines of positioned text, and then on next command I used overlapping position:

![A long text in terminal](https://user-images.githubusercontent.com/5422161/58429052-3f3a6580-80ad-11e9-8506-6cb972b499c4.png)

![New text that replaces part of old one](https://user-images.githubusercontent.com/5422161/58429075-524d3580-80ad-11e9-9433-0d58eaaa3bab.png)

**Comment by andresgongora** [comment]
I'm working on an edited version of status.sh - It does not solve this issue, but it will make it MUCH easier to implement any option we might choose to; be it a matrix implementation or a smart multirow with overlapping text.

**Comment by andresgongora** [comment]
I've taken a look at your exit code suggestion, and its perfect!! Great idea!! :D

**Comment by andresgongora** [comment]
This might be an interesting reference http://bruxy.regnet.cz/web/linux/EN/matrix-sh/

**Comment by andresgongora** [comment]
http://www.termsys.demon.co.uk/vtansi.htm

**Comment by andresgongora** [comment]
So, I'm back from another journey; but I had time to think about the problem and put together all the pieces from our past discussion. The idea would be as follows:



1. Get terminal info: such as size, to compute where we want the logo and the info elements. On a wide terminal, they might be plotted further apart, on a narrow terminal (e.g. 80 chars broad), they should be packed tightly together. On a super narrow terminal, the logo should be omitted altogether. 

2. Draw the logo
   1. Load the logo as a single string, where the end of the logo would obviously be delimited by a `\n`.
   2. Move the cursor to the position where we want the logo to start (upper left corner).
   3. Reformat the logo (sed, tr, awk...) by replacing the new line characters `\n` with an escape character that tells the cursor to go to position `[i+1,c]`; where `i+1` is such that sequential lines are drawn, and `c` is the first column where we want to draw the logo.
   4. Print the reformatted logo. Each new line will start at the correct position.

3. Draw info
   1. Read a configuration line that contains the info elements that the user wants to plot, and their order. For example `stats="os, cpu, gpu, user"` means that the first info line should be OS related info, next line should be CPU info, next line should be GPU info (not implemented yet), and the last should be the USER/HOST info. This way, the user may omit or reorder the lines as wished.
   2. For each word in the above configuration line, call a function that is basically a big switch-case that then calls the appropriate printing helper. But before printing, the cursor is relocated to the current position.

**Comment by andresgongora** [comment]
First working draft in 472d98d

**Comment by andresgongora** [comment]
Solved in #105.
Realized there is a bug (maybe always there?), described in #106.
