### ISSUE TITLE
printTop() fails if $cpu_is_crit is true

### ISSUE THREAD

**Issue by olmari** [andresgongora/scripts#63]
When CPU load average goes above determined critical value, status.sh fails to print proper data and/or prints out also printf error:

![Output error on CPU above critical](https://user-images.githubusercontent.com/5422161/58722782-05d16500-83e1-11e9-9a05-82a34d6777cc.png)

(Logo being improperly aligned is another on-going thing, no need to point that one out)

**Comment by andresgongora** [comment]
I'm 99% confident the bug is fixed.

@olmari I should have asked you to review the merge request, but if you see no trouble with your script the next days, I'll close this issue

**Comment by andresgongora** [comment]
Commit #71

**Comment by olmari** [comment]
Confirmed working in ubuntu 19.04.

![Screenshot from CPU critical](https://user-images.githubusercontent.com/5422161/58822385-06b40200-8640-11e9-9984-53895ca9e56b.png)
