### ISSUE TITLE
status.sh hangs the terminal, gives message "cat: /etc/upstream-release: Is a directory."

### ISSUE THREAD

**Issue by someone7070** [andresgongora/scripts#65]
The script status.sh doesn't work properly for me. It hangs at the very part of the script, where it is looking for OS information. The command "cat /etc/*-release" works fine by itself though, so I guess something is wrong with how my system is interpreting the bash script. Any advice?
I know I can just ctrl-c and stop it, but I'd like to actually see the script run the way it is supposed to.

**Comment by andresgongora** [comment]
Dear someone7070. I'm travelling right now, but I'll try to take a look at it in approx 12 hours. With your description, I think we're the problem lies :)El 1 jun. 2019 0:55, someone7070 <notifications@github.com> escribió:The script status.sh doesn't work properly for me. It hangs at the very part of the script, where it is looking for OS information. The command "cat /etc/*-release" works fine by itself though, so I guess something is wrong with how my system is interpreting the bash script. Any advice?
I know I can just ctrl-c and stop it, but I'd like to actually see the script run the way it is supposed to.

**Comment by andresgongora** [comment]
I forgot to ask. You are using the master branch right? Would you mind testing the develop branch for GitHub and confirm whether the problem persists? Also, what distro are you using?El 1 jun. 2019 0:55, someone7070 <notifications@github.com> escribió:The script status.sh doesn't work properly for me. It hangs at the very part of the script, where it is looking for OS information. The command "cat /etc/*-release" works fine by itself though, so I guess something is wrong with how my system is interpreting the bash script. Any advice?
I know I can just ctrl-c and stop it, but I'd like to actually see the script run the way it is supposed to.

**Comment by someone7070** [comment]
Hi! The development branch gives a slightly different error, and briefly hangs the terminal before displaying properly. It says 'sed: read error on /etc/upstream-release: Is a directory' and then displays the status.sh script normally. Here are the contents of it:

        -oydNMMMMNdyo-        	OS		Linux Mint 19.1
     -yNMMMMMMMMMMMMMMNy-     	Kernel		4.15.0-50-generic
   .hMMMMMMmhsooshmMMMMMMh.   	CPU		Intel(R) Core(TM) i7-9750H CPU
  :NMMMMmo.        .omMMMMN:  	Shell		/bin/bash
 -NMMMMs    -+ss+-    sMMMMN- 	Date		2019.06.01 - 13:49:57
 hMMMMs   -mMMMMMMm-   sMMMMh 	Login		justin@justin-Legion-Y7000-2019-0
'MMMMM.  'NMMMMMMMMN'  .MMMMM'	Local IPv4	192.168.31.232,10.192.0.50
'MMMMM.  'NMMMMMMMMN'   yMMMM'	External IPv4	N/A
 hMMMMs   -mMMMMMMMMy.   -yMh 	SystemCTL	All services OK
 -NMMMMs    -+ss+yMMMMy.   -. 	Sys load avg	[               ] 1 %
  :NMMMMmo.       .yMMMMy.    	Memory		[|              ]  2084/15958 MB
   .hMMMMMMmhsoo-   .yMMMy    	Swap		[               ]     0/2047  MB
     -yNMMMMMMMMMy-   .o-     	Storage /	[|||||          ]    94/248   GB
        -oydNMMMMNd/          	Storage /home	[|||||          ]    94/248   GB

**Comment by olmari** [comment]
Okay I know what causes the problem, we need to narrow down what files we look OS pretty name from. There will be fix soon enough, depending which one of us gets to computer before ;)

**Comment by olmari** [comment]
Fixed in https://github.com/andresgongora/scripts/commit/edb9af68662c0ceb1c06f2057145b136ee5a83a7 Feel free to reopen ticket if issue somehow still isn't gone :)

**Comment by someone7070** [comment]
It still produces the error, and a strange line break, but the status actually loads quickly now.
Terminal output:
`sed: read error on /etc/upstream-release: Is a directory

        -oydNMMMMNdyo-            OS        Linux Mint 19.1
Linux Mint 19.1
     -yNMMMMMMMMMMMMMMNy-         Kernel        4.15.0-50-generic
   .hMMMMMMmhsooshmMMMMMMh.       CPU        Intel(R) Core(TM) i7-9750H CPU
  :NMMMMmo.        .omMMMMN:      Shell        /bin/bash
 -NMMMMs    -+ss+-    sMMMMN-     Date        2019.06.01 - 19:37:47
 hMMMMs   -mMMMMMMm-   sMMMMh     Login        *****@*****-Legion-Y7000-2019-0
'MMMMM.  'NMMMMMMMMN'  .MMMMM'    Local IPv4    192.168.31.232
'MMMMM.  'NMMMMMMMMN'   yMMMM'    External IPv4    121.237.230.155
 hMMMMs   -mMMMMMMMMy.   -yMh     SystemCTL    All services OK
 -NMMMMs    -+ss+yMMMMy.   -.     Sys load avg    [               ] 1 %
  :NMMMMmo.       .yMMMMy.        Memory        [||             ]  2994/15958 MB
   .hMMMMMMmhsoo-   .yMMMy        Swap        [               ]     0/2047  MB
     -yNMMMMMMMMMy-   .o-         Storage /    [|||||          ]    94/248   GB
        -oydNMMMMNd/              Storage /home    [|||||          ]    94/248   GB


 *****  *****-Legion-Y7000-2019-PG0  ~  
`
    On Saturday, June 1, 2019, 1:13:03 PM GMT+2, Sami Olmari <notifications@github.com> wrote:  
 
 
Fixed in edb9af6 Feel free to reopen ticket if issue somehow still isn't gone :)

**Comment by olmari** [comment]
On develop branch?

**Comment by someone7070** [comment]
On the most recent update to status.sh that was done. I copied and pasted the code into the appropriate place in the script and ran it. If it helps at all, my terminal is xfce4-terminal
, which could be producing the error (haven't another one).
    On Saturday, June 1, 2019, 1:43:35 PM GMT+2, Sami Olmari <notifications@github.com> wrote:  
 
 
On develop branch?

**Comment by olmari** [comment]
Hmm, further digging indicates that fix I pushed to develop branch does fix the "`sed: read error on /etc/upstream-release: Is a directory" problem, but there sitll exist something else on CPU detection I think... 

> On the most recent update to status.sh that was done. I copied and pasted the code into the appropriate place in the script and ran it. If it helps at all, my terminal is xfce4-terminal

you can switch branches with `git checkout develop` to get everything needed, and `git pull` in general to update to latest version available (on the branch)

**Comment by olmari** [comment]
After all, it wasn't Mint failing in itself, but apparently some CPU modelnames show wildly diffirently, with and without `@ X.XXGHz`, now we compare and remove speed info only when it is actually there to begin with. Confirmed working on laptop and VM Mint.

Fixed in https://github.com/andresgongora/scripts/commit/4d073d999289b4680ef2214f597a9764ac0986b0
