### ISSUE TITLE
Run scripts from within bashrc instead of sourcing them

### ISSUE THREAD

**Issue by andresgongora** [andresgongora/scripts#78]
- **Advantage:** no user environment contamination with function names and variables

- **Disadvantages**: the script must be ensured to be executables. This was not needed because bashrc is an executable and took care of the "permissions" for us.

**Comment by andresgongora** [comment]
It's quite problematic. Some scripts, like fancy_bash_prompt, MUST be sourced. So, there are two options:

1. All scripts are sourced, but those that don't need it do everything possible to avoid polluting the environment, like wrapping themselves in a single huge function, which then gets called in a subshell, and is finally unset
```
status()
{
##All extra functions here
foo()
{

}

## Main code here
do-status-stuff
foo
}

## Call here
(status)
unset status
```

2. Modify the installer such that some files get sourced, and others instaled

**Comment by olmari** [comment]
I'd vote for the solution 1 in general, but this is only opinion...

Wouldn't it be sufficient to add just that 'unset status' to current end of status.sh?

(Where does current system leaves variables? I see nothing in `export`)

**Comment by andresgongora** [comment]
You would have to unset ALL declared functions manually if not done like in 1. By wrapping all auxiliary function in a master function, their scope gets limited. I'm testing it on `features/cleanup_status` banch

**Comment by andresgongora** [comment]
After some tests, this can be omitted for now. Still, the script should avoid at all cost polluting the user's environment.
