### ISSUE TITLE
Consider making this into two separate repos

### ISSUE THREAD

**Issue by andresgongora** [andresgongora/scripts#89]
1. Repo with all other scripts (which noone uses but me xD) and the common scripts.
2. Repo with status, fancy-bash-prompt installer, config examples. Include first repo as submodule.

@olmari you have more experience. Would it be a good idea? I mean, this way our work could become a "bunch of script" solely aimed at improving the terminal experience; instead of a collection of loose scripts. Also, the installer only installs status and fancy anyway...

Problem is. Can I rename this repo?

**Comment by andresgongora** [comment]
I've found two other scripts that do something similar. Neonfetch and Screenfetch. Both repos are "standalone", which helps new users find their way around :)

But I'm very worried about renaming the repo. Maybe create a new repo, and point this to the new one??

**Comment by andresgongora** [comment]
https://github.com/KittyKatt/screenFetch/blob/master/README.mkdn

I like how you can call the program with several parameters. That's super neat!! They have a great program over there!!

**Comment by olmari** [comment]
I... have no real clue how would this work best :P 

I guess you could just rename it and existing installations fails then `git pull` and such, and say "tough luck" ;) (well make some readme to tell where to go..). You could also make 2 or more new repositories and have them all as subrepositories into main "scripts"...

I have no idea wqhat would be best solution...

**Comment by andresgongora** [comment]
In must be in such a way that this repo does not get altered (other than the name, maybe)

**Comment by andresgongora** [comment]
Ref for the future: https://indieground.net/wp-content/uploads/2018/05/80sfonts_indiegroundblog_ogimage_facebook.jpg
