### ISSUE TITLE
Add GIT related info to fancy-bash-prompt

### ISSUE THREAD

**Issue by andresgongora** [andresgongora/scripts#97]
Original idea by @fikoborizqy in pull request #94 

- [x] Show relative information only when inside a git repository.
- [x] Make prompt shorter to fit that much information by shortening PWD (see #96 for more info).
- [x] Make it user-configurable (on/off).

**Comment by olmari** [comment]
I feel need for enabled/disabled in config (easy one).

Width can be cumbersome.. as a whole promt or additional similar shortener than pwd has or? (Hard one)

**Comment by andresgongora** [comment]
@olmari Added you suggestion of configuration file.

As for "shortening", I mean making PWD shorter as described in #96 (will fix that too in the description)

**Comment by andresgongora** [comment]
Being addressed in #99
